export const words = [
	{ id: 1, english: 'Apple', russian: 'Яблоко' },
	{ id: 2, english: 'Book', russian: 'Книга' },
	{ id: 3, english: 'Cat', russian: 'Кошка' },
	{ id: 4, english: 'Dog', russian: 'Собака' },
	{ id: 5, english: 'House', russian: 'Дом' },
	{ id: 6, english: 'Water', russian: 'Вода' },
	{ id: 7, english: 'Food', russian: 'Еда' },
	{ id: 8, english: 'Friend', russian: 'Друг' },
	{ id: 9, english: 'Love', russian: 'Любовь' },
	{ id: 10, english: 'School', russian: 'Школа' },
	{ id: 11, english: 'Sun', russian: 'Солнце' },
	{ id: 12, english: 'Moon', russian: 'Луна' },
	{ id: 13, english: 'Tree', russian: 'Дерево' },
	{ id: 14, english: 'Car', russian: 'Машина' },
	{ id: 15, english: 'Music', russian: 'Музыка' },
	{ id: 16, english: 'Travel', russian: 'Путешествие' },
	{ id: 17, english: 'Family', russian: 'Семья' },
	{ id: 18, english: 'Happiness', russian: 'Счастье' },
];
